# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: ubuntu-16.04

variables:
  cacheRestored: false

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  persistCredentials: true  # set to 'true' to leave the OAuth token in the Git config after the initial fetch

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    checkLatest: true
  displayName: 'Use Yarn 1.x'

- task: PowerShell@2
  name: setTargetBranchVarStep
  inputs:
    targetType: 'inline'
    script: |
      $targetBranch = '$(System.PullRequest.TargetBranch)' -replace 'refs/heads/',''

      echo "##vso[task.setvariable variable=targetBranch;isOutput=true]$targetBranch"
    pwsh: true

- script: git checkout $(setTargetBranchVarStep.targetBranch)
  displayName: 'git checkout target branch'

- task: PowerShell@2
  name: setSourceBranchVarStep
  inputs:
    targetType: 'inline'
    script: |
      $sourceBranch = '$(System.PullRequest.SourceBranch)' -replace 'refs/heads/',''

      echo "##vso[task.setvariable variable=sourceBranch;isOutput=true]$sourceBranch"
    pwsh: true

- script: git checkout $(setSourceBranchVarStep.sourceBranch)
  displayName: 'git checkout source branch'

- task: CacheBeta@0
  displayName: CacheBeta
  inputs:
    key: '$(System.DefaultWorkingDirectory)/yarn.lock'
    path: '$(System.DefaultWorkingDirectory)/node_modules'
    cacheHitVar: cacheRestored

- script: yarn install
  displayName: 'yarn install'
  condition: and(succeeded(), neq(variables['cacheRestored'], 'true'))

- script: yarn format:check
  displayName: 'yarn format:check'

- script: yarn affected:lint
  displayName: 'yarn affected:lint'

- script: yarn affected:build --prod
  displayName: 'yarn affected:build --prod'

- script: yarn affected:test
  displayName: 'yarn affected:test'

- task: PublishPipelineArtifact@0
  inputs:
    targetPath: 'dist/apps/root-core'
