# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: ubuntu-16.04

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  persistCredentials: true  # set to 'true' to leave the OAuth token in the Git config after the initial fetch

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    checkLatest: true
  displayName: 'Use Yarn 1.x'

- task: PowerShell@2
  name: setTargetBranchVarStep
  inputs:
    targetType: 'inline'
    script: |
      $targetBranch = $(System.PullRequest.TargetBranch) -replace 'refs/heads/',''

      echo "##vso[task.setvariable variable=targetBranch;isOutput=true]$targetBranch"
    pwsh: true

- script: git checkout $(setTargetBranchVarStep.targetBranch)
  displayName: 'git checkout target branch'

- task: PowerShell@2
  name: setSourceBranchVarStep
  inputs:
    targetType: 'inline'
    script: |
      $sourceBranch = $(System.PullRequest.SourceBranch) -replace 'refs/heads/',''

      echo "##vso[task.setvariable variable=sourceBranch;isOutput=true]$sourceBranch"
    pwsh: true

- script: git checkout $(setSourceBranchVarStep.sourceBranch)
  displayName: 'git checkout source branch'

- script: yarn install
  displayName: 'yarn install'

- script: yarn format:check
  displayName: 'yarn format:check'

- script: yarn lint
  displayName: 'yarn lint'

- script: yarn build:prod
  displayName: 'yarn build:prod'

- script: yarn test:prod
  displayName: 'yarn test:prod'

- task: PublishPipelineArtifact@0
  inputs:
    targetPath: 'dist/apps/root-core'
