# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: ubuntu-16.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    checkLatest: true
  displayName: 'Use Yarn 1.x'

- script: yarn install
  displayName: 'yarn install'

- script: yarn format:check
  displayName: 'yarn format:check'

- script: yarn lint
  displayName: 'yarn lint'

- script: yarn build:prod
  displayName: 'yarn build:prod'

- script: yarn test:prod
  displayName: 'yarn test:prod'

- script: yarn e2e
  displayName: 'yarn e2e'

- task: PublishPipelineArtifact@0
  inputs:
    targetPath: 'dist/apps/root-core'