version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:10-browsers-legacy
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Show current directory
                command: pwd
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Install dependencies
                command: yarn
            - save_cache:
                key: v1-dependencies-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules
            - run:
                name: Linting
                command: yarn lint
            - run:
                name: Formatting
                command: yarn format:check
            - run:
                name: Testing
                command: yarn test:prod
            - run:
                name: Set Config
                command: base64 --decode $CONFIG_FILE >> ./apps/root-core/src/config/production.json
            - run:
                name: Building
                command: yarn build:prod
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
                    - package.json
                    - yarn.lock
                    - firebase.json
                    - .firebaserc
    deploy:
        docker:
            - image: circleci/node:10-browsers-legacy
        working_directory: ~/project
        steps:
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install Firebase
                command: yarn add firebase-tools --dev
            - run:
                name: Deploy master to Firebase
                command: yarn firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master
