version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: cimg/node:14.16.0-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Show current directory
                command: pwd
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Install dependencies
                command: yarn
            - save_cache:
                key: v1-dependencies-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules
            - run:
                name: Linting
                command: yarn affected:lint
            - run:
                name: Formatting
                command: yarn format:check
            - run:
                name: Testing
                command: yarn affected:test
            - run:
                name: Building
                command: yarn build:prod

workflows:
    version: 2
    -deploy:
        jobs:
        - build
