version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

    ports:
      - "35729:35729"
      - "4200:4200"

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
